### ISSUE TITLE
TSC Meeting (03 May 2022): self-check in GH Actions, AWS cost reduction follow-up, v3.7.0 release

### ISSUE THREAD

**Issue by winem** [StackStorm/discussions#100]
May 2022 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `03 May 2022, 09:30 AM US Pacific`.

See #33 for more info on how to join.
(TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09)

### StackStorm AWS cost-reduction project ~(5min)
  - See the previous meeting for the issue description and more context: https://github.com/StackStorm/community/issues/97
  - Project: https://github.com/orgs/StackStorm/projects/27
  - Follow-up on the first batch of distributed tasks ([Slack link](https://stackstorm-community.slack.com/archives/C020U70RZRR/p1646333439674819)):
    - [x] [Migrate internal monitoring server to free 3rd party service (Scalyr)](https://github.com/StackStorm/st2ci/issues/208) (@Kami)
    - [x] Replace paid RHEL8 to free Rocky8 e2e testing [[1]](https://github.com/StackStorm/st2cd/pull/470) [[2]](https://github.com/StackStorm/st2ci/pull/209) (@amanda11) 
    - [x] AWS Route53 cleanup, Right-size the AWS e2e and VPN instances (-$120/mo) (@armab)
    - [ ] [In progress: run st2-self-check in GH Actions, instead of st2cicd e2e tests](https://github.com/StackStorm/st2/issues/5496) (@winem)
    - [ ]  [Migrate api.stackstorm.com to GH static pages](https://github.com/StackStorm/st2apidocs/issues/16) (@bishopbm1)
    - [ ] [Experiment with the AWS spot instances for running e2e test VMs: U16,U18,EL7,EL8](https://github.com/orgs/StackStorm/projects/27#card-78437979) (@punkrokk)
    - [ ]  [Migrate docs.stackstorm.com to GH static pages #1096](https://github.com/StackStorm/st2docs/issues/1096) (@guzzijones)

### Drop Python 3.6 / OS support matrix ~(10m)
  - Python 3.8 is not available in CentOS 7 without building/distributing our own.
  - Is there a way to divorce our requirements from OS platforms and focus more on supporting various python versions? (3.9, 3.10)

### StackStorm `v3.7.0` release preparation ~(5min)
  - Release Manager: @cognifloyd, Release Assistant: @nzlosh
  - Target month:  May 2022?
  - Project & Roadmap: https://github.com/orgs/StackStorm/projects/23
  - JS Review needed on: https://github.com/StackStorm/st2web/pull/863
  - @amanda11 s blog post for the new override feature: https://docs.google.com/document/d/1boNJiuNu--Ob1xGDf5eGWxf-2yAIF70fbYFmqut91uI/edit?usp=sharing 
  (- Who is going to be the release manager and assistant for `v.3.8.0`?)

### [TSC Meeting host rotation](https://github.com/StackStorm/community/issues/4) ~(5min)
  - Proposal: Start with the rotation in June 2022 with one of the 3.7.0 release managers (see https://github.com/StackStorm/community/issues/4#issuecomment-1090215273)
  
### [ST2 Security/Maintenance Project](https://github.com/orgs/StackStorm/projects/25) ~(10min)
  - How well did requiring 2 PR reviews on the st2 repo go this month? Any lessons learned?
  - Should we do the same for other repos?
  - Pick one item from the https://github.com/orgs/StackStorm/projects/25 and discuss/triage it

**Comment by winem** [comment]
Following topics were moved to the next TSC meeting in June:

### Demo: migration to Scalyr monitoring for internal st2cicd infra by @Kami ~(10min)
  - See: https://github.com/StackStorm/st2ci/issues/208
  - Highlight the new system, dashboards, monitors, how to operate it, and use it collectively as @StackStorm/maintainers

### Run st2-self-check in GH Actions ~(5min)
  - current state of the PR https://github.com/StackStorm/st2/issues/5496
  - how to handle tests with HTTP actions - the only ones that still fail
  - agree on the MVP to start with the self-check in GH Actions (older Python versions seem to be a problem, I'll provide details during the meeting)

**Comment by winem** [comment]
Meeting notes: 

Attendees: 
@armab @amanda11 @cognifloyd @rush-skills  @winem @nzlosh

### Migrating AWS parent org to Encore ~(10m)
- We'll coordinate this async to the TSC meetings
  - The credit card on the root account needs to be changed before the account will be transfered to Encore 
- Given that the AWS credits expire in a few months it was discussed whether AWS is the right cloud provider for us
  - there are multiple maintainers with AWS knowledge, so there is no risk due to a lack of knowledge 
  - other cloud providers like GCP and Azure were briefly evaluated in the past and we'll probably have similar challenges regarding the OSS credits

### Drop Python 3.6 / OS support matrix ~(10m)
- CentOS 7 will be EOL June 2024; Py3.8 will not be available on CentOS7 
- The participants agreed that we do not want to provide any kind of home grown Python-environment or solution to run a higher Python version on CentOS7
- It was also discussed to provide st2 just as Docker containers and have that as the only supported installation method
  - Pros: 
    - This would save us some of the bundling, packaging and distribution pain
  - Cons:
    - This will break installations for deployments out there (i.e., bare metal deployments)
    - Such a change can only be done with a major version change and will not be possible in the short term
- conda as alternative to pip which also manages the Python environment was also discussed to distribute the st2 Python packages, but we want to avoid that
- The high number of Python version we may have to support in the future raised some concerns:
  - Python3.6 would be required for CentOS7 support
  - Python3.7 would allow us to support Ubuntu 18.04
  - Python3.8 would at least be required for Ubuntu 20 and CentOS8
  - Python3.9 would be needed to support Debian 11
  - Python3.10 would be needed to run st2 on Ubuntu 22


----------------------------------------------

Draft for the next TSC meeting agenda: 
### StackStorm AWS cost-reduction project ~(5min)
  - See the previous meeting for the issue description and more context: https://github.com/StackStorm/community/issues/97
  - Project: https://github.com/orgs/StackStorm/projects/27
  - Follow-up on the first batch of distributed tasks ([Slack link](https://stackstorm-community.slack.com/archives/C020U70RZRR/p1646333439674819)):
    - [x] [Migrate internal monitoring server to free 3rd party service (Scalyr)](https://github.com/StackStorm/st2ci/issues/208) (@Kami)
    - [x] Replace paid RHEL8 to free Rocky8 e2e testing [[1]](https://github.com/StackStorm/st2cd/pull/470) [[2]](https://github.com/StackStorm/st2ci/pull/209) (@amanda11) 
    - [x] AWS Route53 cleanup, Right-size the AWS e2e and VPN instances (-$120/mo) (@armab)
    - [ ] [In progress: run st2-self-check in GH Actions, instead of st2cicd e2e tests](https://github.com/StackStorm/st2/issues/5496) (@winem)
    - [ ]  [Migrate api.stackstorm.com to GH static pages](https://github.com/StackStorm/st2apidocs/issues/16) (@bishopbm1)
    - [ ] [Experiment with the AWS spot instances for running e2e test VMs: U16,U18,EL7,EL8](https://github.com/orgs/StackStorm/projects/27#card-78437979) 
    - [ ]  [Migrate docs.stackstorm.com to GH static pages #1096](https://github.com/StackStorm/st2docs/issues/1096) (@guzzijones)

### Demo: migration to Scalyr monitoring for internal st2cicd infra by @Kami ~(10min)
  - See: https://github.com/StackStorm/st2ci/issues/208
  - Highlight the new system, dashboards, monitors, how to operate it, and use it collectively as @StackStorm/maintainers

### Run st2-self-check in GH Actions ~(5min)
  - current state of the PR https://github.com/StackStorm/st2/issues/5496
  - how to handle tests with HTTP actions - the only ones that still fail
  - agree on the MVP to start with the self-check in GH Actions (older Python versions seem to be a problem, I'll provide details during the meeting)
