### ISSUE TITLE
TSC Meeting (13 Jul 2021): v3.5 Released 🎉, v3.6 Roadmap Planning, Maintenance

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#83]
> **NOTE!** 
> Due to US holiday, TSC requested to move the meeting. New date is `13th July` instead of 6th.

July 2021 @StackStorm/tsc `1 hour` meeting will take place on Tuesday, `13th July 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda

- News/Announcements *(3min)*
- StackStorm `v3.5.0` was released 🎉 *(10min)*
  - Release Manager @amanda11, Release Assistant: @winem 
  - Feedback, Retrospective from the team?
    - what went well
    - what didn't?
  - Post-release: update st2cicd to the latest dev version?
- StackStorm `v3.6.0` Roadmap planning *(25min)*
  - Target date: (3mo)?
  - Release Manager: @winem (based on [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - Release Assistant: WHO @StackStorm/maintainers?
  - What was @StackStorm/maintainers and Partners impact in `v3.5.0`?
  - What are @StackStorm/maintainers and Partners plans for `v3.6.0`?
  - [Roadmap WIP](https://github.com/orgs/StackStorm/projects/22)
  - ChatOps
    - short-term: Node 14 -> 16 update ?
    - long-term: Python ChatOps discussion?
- StackStorm Partners Program was shipped 🎉 *(5min)*
  - Coordinator: @mickmcgrath13 
  - https://stackstorm.com/
  - https://stackstorm.com/partners/
  - https://stackstorm.com/partners-program/
- [StackStorm Infra & Expenses](https://github.com/StackStorm/discussions/issues/36) *(10min)*
  - AWS account expenses, FOSS credits (@punkrokk)
  - PackageCloud.io paid plan (#74)
  - Infra/Maintenance: stackstorm.com website migration to static pages #76
  - Infra/Maintenance: Forum -> Github Discussions migration #75
- Any other random Questions and Discussions *(5min)*
  - Officially relaxing our governance requirements document (@blag)

**Comment by arm4b** [comment]
FYI due to US holiday, TSC requested to move the meeting. New date is `13th July`.

@StackStorm/tsc @StackStorm/contributors

**Comment by arm4b** [comment]
## Participants
Host: @armab
Attendees: @blag @amanda11 @winem @punkrokk @cognifloyd + :bust_in_silhouette:  1 community


## Meeting Minutes

### Project Updates
- Congratulations @arms11 for becoming one of the st2 @StackStorm/contributors  https://github.com/StackStorm/st2/pull/5288
- Thanks @cognifloyd from @StackStorm/contributors for shipping 15+ PRs to st2 K8s Helm chart
  - opportunity to promote K8s chart `beta` -> `stable` later: https://github.com/stackStorm/stackstorm-ha
- Encore is helping around the Puppet-st2 maintenance
- We applied to Docker Open Source program and they whitelisted https://hub.docker.com/r/stackstorm/ org. No rate limiting for users downloading st2 images whatsoever.


### StackStorm v3.5.0 release
- StackStorm v3.5.0 is out :tada: !
- Thanks @amanda11 and @winem for their hard work leading it!
- Feedback:
  - low participation from @stackstorm/tsc in the pre-release testing

### Random Discussion: Release Cadence
- How to make releases easier and faster?
  - how about weekly/on-demand releases when needed?
- Note: 1 yr old first community release feedback to do faster release cadence: https://github.com/StackStorm/discussions/issues/20
- Note: Sept 2020 we moved to lower 3mo release cadence: https://github.com/StackStorm/discussions/issues/50
- Problem: Hard to find release manager/coordinator, releases are too time-consuming, a major effort
- Observation: Historically being a company-supported product, StackStorm still has a lot of Q/A processes that require full-time effort and maintenance
  - it shouldn't be that hard for OSS community to manage it
  - reduce the quality bar, ship faster?
- Minimize Release complexity, Change the approach? 
  - simplify st2cicd workfows and number of moving pieces?
  - rely more on python packaging solutions?
  - ditch the `deb`/`rpm` packages? Let the users build st2 from sources or maybe partners to provide packaging solutions?
  - remove the manual Q/A pre-release testing process?
  - remove st2cicd, rely on CircleCI only?
  - remove environments and package promotion complexity: `staging`, `unstable`, `staging-unstable`, `staging-stable`?
- @punkrokk will provide a Github Discussion with the hot topic for others to get involved & gather feedback and proposals

### Random Discussion: It's hard to setup st2 Development environment to contribute a first PR
- Provide a `Vagrantfile` in stackstorm/st2? https://github.com/StackStorm/st2vagrant/
- Provide a `docker-compose` file in stackstorm/st2? https://github.com/stackStorm/st2-docker

### StackStorm `v3.6.0` release planning - _moved to August TSC Meeting_
- Release manager: @winem. Release assistant: WHO from @StackStorm/tsc?
- Maintenance release? Just ship what was merged before the release date?
- When? (+3 mo or different?)
- Due to low TSC presence, release planning _moved to the next August TSC Meeting_

### StackStorm Partners Program
- StackStorm Partners Program was officially shipped https://stackstorm.com/partners/ :tada: 
  - Thanks @mickmcgrath13 for brilliantly leading it  :+1: 
  - @armab  to follow-up on announcing it to ST2 OSS Community.

### Project Expenses - _re-iterate at August TSC Meeting_
#### AWS
  - We burned all the CommunityBridge donated $ due to the most recent `2` x `$600`+ bills
    - FOSS program 2-month lag, AWS being slow on renewing FOSS credits
  - https://crowdfunding.lfx.linuxfoundation.org/projects/aec7b5bf-bb7a-4385-9820-eaef4e92bcfa (numbers are not updated yet, but it's close to 0).
  - @punkrokk reports AWS promised to apply the AWS credits last week
  - AWS confirmed: 2021 is the last year of FOSS credits
    - @punkrokk suggested to further minimize the AWS costs where possible
  - Biggest $ back hole: Running full st2 e2e tests on 4 platforms by spinning fresh VM instances: U16/U18, EL7/EL8
  - Team agreed to switch from nightly to weekly CI/CD e2e builds & tests (Done :heavy_check_mark:  by @amanda11: https://github.com/StackStorm/st2cd/pull/466)
  - @punkrokk will provide a PR to run builds on AWS spot instances instead of using EC2 on-demand (repo: https://github.com/StackStorm/st2ci/)
#### PackageCloud
  - Hidden complexity of moving to other deb/rpm provider: rework st2cicd workflows, create new st2 integration pack, releases, st2cicd, update users with the new URL
  - With no $ on CommunityBridge and with the new official st2 Partners Program, reiterate with PackageCloud on FOSS program (we pay ~$120/mo)
  - Last 14 month of PackageCloud BW usage was below the FOSS limits ([Screenshot](https://user-images.githubusercontent.com/1533818/125513732-2f6f5855-9c53-4c17-b3b7-11ff1414a506.png)) 
  - TODO: Clean up unused deb/rpm packages ([Screenshot](https://user-images.githubusercontent.com/1533818/125513492-6a406280-7fdb-4b48-a31e-79f6cdbd9e40.png))
### forum.stackstorm.com migration to GH Discussions - _moved to August TSC Meeting_
### stackstorm.com migration to GH static pages - _moved to August TSC Meeting_
### Relaxing ST2 Governance for Maintainers - _moved to August TSC Meeting_
  - Problem: The requirements to join the TSC and become a StackStorm Maintainer are too high
  - https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-to-become-a-maintainer
  - Due to low TSC quorum, discussed has been _moved to August TSC Meeting_

## Actionable Items:
- [ ] StackStorm Partners Program: @armab will work on announcing it to st2 OSS Community
- [x] Faster StackStorm Releases: @punkrokk will provide a focused Github Discussion with the topic for others to provide feedback and get involved
- [x] ~Reduce AWS $:  @amanda11 to switch from nightly to weekly CI/CD builds~ (Done :heavy_check_mark:: https://github.com/StackStorm/st2cd/pull/466)
- [ ] Reduce AWS $: @punkrokk will provide a PR to run builds on AWS spot instances instead of on-demand (repo: https://github.com/StackStorm/st2ci/)
- [ ] PackageCloud: Clean up unused `deb`/`rpm` packages. WHO @StackStorm/tsc ?
