### ISSUE TITLE
TSC Meeting (05 Apr 2022): Scalyr Monitoring, AWS cost reduction, v3.7.0 release

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#99]
April 2022 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `05 Apr 2022, 09:30 AM US Pacific`.

See #33 for more info on how to join.
(TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09)

### Demo: migration to Scalyr monitoring for internal st2cicd infra by @Kami ~(10min)
  - See: https://github.com/StackStorm/st2ci/issues/208
  - Highlight the new system, dashboards, monitors, how to operate it, and use it collectively as @StackStorm/maintainers

### [TSC Meeting host rotation](https://github.com/StackStorm/community/issues/4) ~(5min)
  - Proposal: document in the Governance TSC Meeting host rotation

### StackStorm AWS cost-reduction project ~(15min)
  - See the previous meeting for the issue description and more context: https://github.com/StackStorm/community/issues/97
  - Project: https://github.com/orgs/StackStorm/projects/27
  - Follow-up on the first batch of distributed tasks ([Slack link](https://stackstorm-community.slack.com/archives/C020U70RZRR/p1646333439674819)):
    - [x] [Migrate internal monitoring server to free 3rd party service (Scalyr)](https://github.com/StackStorm/st2ci/issues/208) (@Kami)
    - [x] Replace paid RHEL8 to free Rocky8 e2e testing [[1]](https://github.com/StackStorm/st2cd/pull/470) [[2]](https://github.com/StackStorm/st2ci/pull/209) (@amanda11) 
    - [x] AWS Route53 cleanup, Right-size the AWS e2e and VPN instances (-$120/mo) (@armab)
    - [ ] [In progress: run st2-self-check in GH Actions, instead of st2cicd e2e tests](https://github.com/StackStorm/st2/issues/5496) (@winem)
    - [ ]  [Migrate api.stackstorm.com to GH static pages](https://github.com/StackStorm/st2apidocs/issues/16) (@bishopbm1)
    - [ ] [Experiment with the AWS spot instances for running e2e test VMs: U16,U18,EL7,EL8](https://github.com/orgs/StackStorm/projects/27#card-78437979) (@punkrokk)
    - [ ]  [Migrate docs.stackstorm.com to GH static pages #1096](https://github.com/StackStorm/st2docs/issues/1096) (@guzzijones)

### StackStorm `v3.7.0` release preparation ~(20min)
  - Release Manager: @cognifloyd, Release Assistant: @nzlosh
  - Target month: March -> April 2022
  - Project & Roadmap: https://github.com/orgs/StackStorm/projects/23
  - Any missing PRs/items/blockers?
  - Tentative week for starting the release automation workflows
  
### [ST2 Security/Maintenance Project](https://github.com/orgs/StackStorm/projects/25) ~(10min)
  - Pack one item from the https://github.com/orgs/StackStorm/projects/25 and discuss/triage it

**Comment by cognifloyd** [comment]
## Meeting notes

### Demo: migration to Scalyr monitoring for internal st2cicd infra by @Kami

Skipped. @Kami was unable to attend.

### [TSC Meeting host rotation](https://github.com/StackStorm/community/issues/4)

- Generally agreed: Rotate Meeting Host
- As this is monthly, TSC maintainers would be hosting the meeting about twice per year.
- We need to create the meeting host rotation. Please post recommendations on who and what order in https://github.com/StackStorm/community/issues/4

### StackStorm AWS cost-reduction project

- Reviewed recently completed tasks.
- Need more reviews + help w/ running remote/ssh tests in https://github.com/StackStorm/st2/pull/5609 (part of https://github.com/StackStorm/st2/issues/5496)
- @bishopbm1 will work on https://github.com/StackStorm/st2apidocs/issues/16 this month (April)
- @guzzijones will work on https://github.com/StackStorm/st2docs/issues/1096 this month (April)
- No updates on other tasks.

### StackStorm `v3.7.0` release preparation

Target master feature freeze date: **15 April 2022**
Target release week: **18-22 April 2022**

- Many PRs merged or closed.
- Need reviews on:
    - https://github.com/StackStorm/st2/pull/5321
    - https://github.com/StackStorm/st2/pull/5319
- JavaScript reviews needed in st2web (finish/merge one of these before 3.7):
    - https://github.com/StackStorm/st2web/pull/722
    - https://github.com/StackStorm/st2web/pull/863
- :tada: Last task in https://github.com/StackStorm/community/issues/88 has a WIP PR: https://github.com/StackStorm/puppet-st2/pull/348
- **_BLOCKER_**: st2chatops CI is broken. @armab to take a look at alternative fixes.
    - See series of recent test builds: https://app.circleci.com/pipelines/github/StackStorm/st2chatops?filter=all
    - See discussion in #development: https://stackstorm-community.slack.com/archives/CSBELJ78A/p1649144663845239

### Highlight awesome recent contributions

TSC maintainers need to review these new contributors/maintainers:
- https://github.com/StackStorm/st2/pull/5613
- https://github.com/StackStorm/st2/pull/5612
- https://github.com/StackStorm/st2/pull/5611
- https://github.com/StackStorm/st2/pull/5610

### [ST2 Security/Maintenance Project](https://github.com/orgs/StackStorm/projects/25)

Things are improving:
- All TSC members now have 2FA enabled
- StackStorm-Exchange migrated to Github Actions with a much better security profile than how we managed things in CircleCI

Discussed "Require 2 reviews per PR for critical st2 repos"

- Drawing the line between what is and is not critical is a sticky question. eg what about the st2-rbac repo where we include the master branch at release time?
- Eugen defined "critical": The repos that build/push artifacts to PackageCloud (st2, st2chatops, st2-packages)
- **Agreed**: Increase required reviews on st2 repo this month. Review in next TSC meeting.
    - @armab to increase required review count on st2 repo to 2.
- **Agreed**: 2 reviews not required on docs repo for security. It would still be nice for quality control.
- TSC members need to review things they are not familiar with to become more familiar and spread knowledge. But we also need to make sure someone else that knows that section of code also reviews it.
- Several people noted that just increasing the required reviews count does not make those reviews actually focus on security. So, we need to document and build culture around including security in reviews.
- Using Github's CODEOWNERS feature may be part of ensuring some people review key sections, but that's more for vision/performance of certain pieces, not necessarily for security.

### Highlight issues for next meeting

- Migrating AWS parent org
- When to drop Python 3.6 / change OS Support matrix

## Draft Agenda for next meeting on 03 May 2022

### Demo: migration to Scalyr monitoring for internal st2cicd infra by @Kami ~(10min)

- See: https://github.com/StackStorm/st2ci/issues/208
- Highlight the new system, dashboards, monitors, how to operate it, and use it collectively as https://github.com/orgs/StackStorm/teams/maintainers

### Plan migration of AWS parent org to Oncore ~(15min)

### Discuss plan for dropping python 3.6 / OS support matrix ~(15 min)

- Python 3.8 is not available in CentOS 7 without building/distributing our own.
- Is there a way to divorce our requirements from OS platforms and focus more on supporting various python versions? (3.9, 3.10)

### Recap on releasing `v3.7.0` / Begin planning `v3.8.0` ~(10 min)

- How did the release go? Lessons learned?
- Who is going to be release manager + assistant release manager for `v3.8.0`?

### [ST2 Security/Maintenance Project](https://github.com/orgs/StackStorm/projects/25) ~(10 min)

- How well did requiring 2 PR reviews on the st2 repo go this month? Any lessons learned?
- Should we do the same for other repos?
- Pick one item from the https://github.com/orgs/StackStorm/projects/25 and discuss/triage it

**Comment by arm4b** [comment]
Meeting attendees for the record.

TSC Meeting Host:
- @cognifloyd 

@StackStorm/maintainers & @StackStorm/contributors:
- @amanda11 @armab @nzlosh @guzzijones @mickmcgrath13 @bishopbm1 @rush-skills @khushboobhatia01
